nav:
  - index.md
  - Обучение: tutorial
  - Рецепты: how-to
  - Справочник: reference
  - Как это устроено: explanation
  - Ошибки: errors
  - Справочник API: api
  - Разработка: contributing
  - Изменения: changelog.md
